/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HappyCustomersRouteImport } from './routes/happy-customers'
import { Route as IndexRouteImport } from './routes/index'

const HappyCustomersRoute = HappyCustomersRouteImport.update({
  id: '/happy-customers',
  path: '/happy-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/happy-customers': typeof HappyCustomersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/happy-customers': typeof HappyCustomersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/happy-customers': typeof HappyCustomersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/happy-customers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/happy-customers'
  id: '__root__' | '/' | '/happy-customers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HappyCustomersRoute: typeof HappyCustomersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/happy-customers': {
      id: '/happy-customers'
      path: '/happy-customers'
      fullPath: '/happy-customers'
      preLoaderRoute: typeof HappyCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HappyCustomersRoute: HappyCustomersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
